### PR TITLE
Add requirement for conda maintainers to use commit signing

### PR DESCRIPTION
**Pull request by travishathaway**
This is a proposal to start requiring conda maintainers to use commit signing. I also added that we strongly recommend other contributors to do this as well.

### CODE REVIEW

**Comment by awwad** [comment]
Some responses to asked questions in the community mtg, and some other FAQs from prior efforts in other projects:

Question 1: **signing vs signoff**
- This effort would be about commit signing (`git commit -S` or `--gpg-sign`), not signoff (`git commit -s` or `--signoff`).  Signoff is essentially a liability/policy thing: all it does is add a line of text to your commit message that says "Signed off by ...".  It's just you providing an attestation that you approve this commit.  There's no security element / verification.  Commit signing, instead, is the creation of a cryptographic signature that is included with your commit and which can be used by anyone to confirm that the commit has not been tampered with since signing (as long as you know the expected key and that expected key has not been compromised -- see below).  I use both by default.

For the rest of these answers, try to imagine two separate questions:
- does this commit match this signature from this key?
- is that key trustworthy for this repository?


Question 2: **git vs GitHub**
- **just plain git**:  (local signing, `gpg` for key trust, local verifying)
   - Without GitHub involvement, signing and verifying commits is supported in git, and git will use your GPG/OpenPGP keychain (if you have it installed) to check to see if you trust the key and if the signature is correct.  This means that without GitHub, you need to use GPG (or your special setup) to verify signatures and manually maintain trust for keys.  This is what makes signing parties relevant.  This is useful for a maximum security model, but it's a huge hassle for the general public (in other words, nobody will use it), though it can be useful for maintainers.  `git log` commands are easily aliased to show commit signature status (can share my config if anyone wants).
- **what GitHub adds**:    (local or remote signing, remote verifying)
   - GitHub does some additional work on the signing side and on the verification side.  Both make it dramatically easier for people to verify things, though the easy ways mostly provide slightly weaker security guarantees.
      - what GitHub adds to the signing side of the process:
         - if web interface, GitHub signs:  for any commit you make through the GitHub web interface (probably also any GitHub CLI), it is not possible for you to sign the commit yourself, so GitHub will sign it for you, using GPG keys they maintain.  Note that any tampering that occurs on the GitHub side (with some agent compromise) or between you and GitHub (if there's a transport security compromise) is therefore not protected against.   is made with your GitHub user authentication, and GitHub registers that.  (It will appear as "verified" 
     - what GitHub adds to the verification side of the process:
         - Badges and automatic verification with GitHub's key registration.  The interface will provide a "verified" badge for the commit you see if it has been signed with a key registered with GitHub or if the commit was made through GitHub's web interface.  Note that these appear the same, but have different security guarantees.  In addition, tampering is possible if an agent on GitHub's side is compromised or if there is a compromise in transport between you and GitHub.  Still, this adds a lot and is lovely. :)

Question 3: **key envelope types -- ssh keys vs gpg keys**
- Both are fine.  GitHub supports registration of gpg keys for gpg signing, and also registration of ssh keys for signing using ssh keys (not the original purpose of ssh keys, of course, but perfectly fine).  Both work equally well on GitHub.  Git also supports this use, if you're doing the clunkier, higher security checks locally -- but I haven't used ssh keys locally, so I can't speak to this.

**Comment by awwad** [comment]
Oh, separately:  this is an extremely good thing to do.  Many thumbs up.

**Comment by dholth** [comment]
If you develop remotely or in a docker container, do you just import those commits back out to the host OS and redo the signing?

**Comment by awwad** [comment]
I usually develop on my host system, test on a VM (one-way shared folder or single-command deploy), and sign on the host system.  I'm not sure what you'd want to do with docker, but I don't think it's useful to sign in the lower-security environment and then re-sign -- just sign when it's safe.  (Did that answer the question?)

**Comment by dholth** [comment]
So I could shell into a system with ssh forwarding, push up to github, download the branch to OSX, run (which command?) to sign those commits, and then push it back up to github?

**Comment by awwad** [comment]
Oh.  You're pushing to GitHub from the docker container?  That's adding a lot of steps for tampering to occur as it travels all around the internet and comes back to you before it's signed.  Maybe it's worth it?

**Comment by awwad** [comment]
As to your question about which command:  if it's one commit, `git commit --amend -s -S`.  If it's a bunch, you'll want to rebase, and use that rebase setup that lets you edit each commit as you go.  I can't remember what that is.

**Comment by dholth** [comment]
It's pretty usual to remote into a server like zeus or a docker container, and use ssh agent forwarding to interact with github. Hopefully git can talk to the ssh agent, ask it to sign things, and go from there? Alternatively could commit on the server, git pull from the server, amend, etc.

**Comment by dholth** [comment]
I think I understand the threat model. Anyone can claim to have any e-mail or date in git. No need to make life inconvenient by trying to protect against compromised github or servers; potentially useful to protect against random person including your email in a long history in a PR.

**Comment by dbast** [comment]
We currently squash the history of all PRs on merge, making all signatures either going away or invalid.

The more important thing to protect against threads is that main branches can be only changed via PRs (without admin exceptions!) and a reviews by at least a second pairs of eyes being required.

**Review by beeankha — APPROVED** [review]

**Review by kenodegard — APPROVED** [review]
Wont hurt to require.

**Pull request merged**
